import httpx


async def execute_plan(plan: dict) -> dict:
    """
    Execute the action plan generated by the planner.
    
    Args:
        plan: Dictionary containing action, target, and reason
        
    Returns:
        Dictionary with execution status and details
    """
    action = plan.get('action')
    
    if action == 'restart_service':
        target = plan.get('target', 'unknown')
        
        try:
            # Send POST request to the chaos-app service
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post("http://chaos-app:8000/chaos/resolve")
                
                if response.status_code == 200:
                    return {
                        'status': 'success',
                        'details': 'Service restarted successfully'
                    }
                else:
                    return {
                        'status': 'error',
                        'details': f'Restart failed with status {response.status_code}'
                    }
                    
        except Exception as e:
            return {
                'status': 'error',
                'details': str(e)
            }
    
    elif action == 'escalate':
        # Escalation doesn't require execution, just notification
        return {
            'status': 'skipped',
            'details': 'Escalation logged for human review'
        }
    
    # Unknown action
    return {
        'status': 'skipped',
        'details': 'No execution path for this action'
    }
